#!/bin/bash
# pack-and-test.sh — Build + pack the SDK and install it into the example app
# from the resulting tarball, simulating an end-user `npm install`.
#
# Why: in workspace mode (default dev flow) the example app resolves the SDK
# through a yarn-workspace symlink, which means Metro consumes `src/index.tsx`
# directly and iOS/Android autolinking sees the repo root. End users on npm
# install get the `lib/` build output and the `files`-allowlisted subset of
# the repo, with native paths resolving from `node_modules`. Differences in
# the published surface (missing `files` entries, stale type defs, podspec
# path assumptions) only show up under the packed install.
#
# Usage:
#   ./pack-and-test.sh setup     # build + pack + swap example to packed mode
#   ./pack-and-test.sh restore   # revert example to workspace mode
#   ./pack-and-test.sh status    # report current mode (workspace / packed)
#
# After `setup`, run `yarn example ios|android` (or `yarn example build:ios`
# / `build:android` for non-interactive verification). When done, run
# `restore` to reinstall workspace mode.
#
# CI usage:
#   - name: Pack + swap to packed install
#     run: ./pack-and-test.sh setup
#   - name: Build example app (Android / iOS / etc.)
#     run: yarn example build:android   # or whatever the target is
#   - name: Restore workspace mode
#     if: always()
#     run: ./pack-and-test.sh restore

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXAMPLE="$ROOT/example"
TARBALL_DIR="$ROOT/.tarballs"
PKG_BACKUP="$EXAMPLE/package.json.workspace-backup"
LOCK_BACKUP="$ROOT/yarn.lock.workspace-backup"
RNCFG_BACKUP="$EXAMPLE/react-native.config.js.workspace-backup"
MARKER="$ROOT/.pack-mode-active"

usage() {
  sed -n '/^# Usage:/,/^$/p' "${BASH_SOURCE[0]}" | sed -E 's/^# ?//'
  exit "${1:-1}"
}

require_tool() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Error: required tool not found: $1" >&2
    exit 1
  }
}

# Tracks how far setup got, so on_error knows whether to attempt a restore.
SETUP_PROGRESS="none"

on_error() {
  local code=$?
  echo >&2
  echo "✗ Failed at stage: $SETUP_PROGRESS (exit $code)" >&2
  case "$SETUP_PROGRESS" in
    swapped|installed|pods)
      echo "  Working tree was modified — attempting automatic restore." >&2
      cmd_restore || echo "  Automatic restore also failed; run \`$0 restore\` manually." >&2
      ;;
    *)
      echo "  No working-tree changes to roll back." >&2
      ;;
  esac
  exit "$code"
}

cmd_setup() {
  trap on_error ERR

  if [[ -f "$MARKER" ]]; then
    echo "Already in packed mode (marker present at $MARKER)." >&2
    echo "Run \`$0 restore\` first, then re-run setup." >&2
    exit 1
  fi

  require_tool jq
  require_tool yarn
  require_tool shasum
  require_tool bundle

  echo "==> Cleaning previous artifacts"
  rm -rf "$ROOT/lib" "$TARBALL_DIR"
  mkdir -p "$TARBALL_DIR"

  SETUP_PROGRESS="building"
  echo "==> Building published artifacts (yarn run prepare)"
  (cd "$ROOT" && yarn run prepare)

  SETUP_PROGRESS="packing"
  echo "==> Packing tarball"
  local raw_tarball="$TARBALL_DIR/klaviyo-react-native-sdk.tgz"
  (cd "$ROOT" && yarn pack --out "$raw_tarball")

  # Yarn 3 caches `file:` deps by URL — re-using the same path on every run
  # silently serves stale cached content. Hash the tarball into the filename
  # so each pack is a distinct cache identity.
  local hash
  hash=$(shasum -a 256 "$raw_tarball" | cut -c1-12)
  local tarball="$TARBALL_DIR/klaviyo-react-native-sdk-$hash.tgz"
  mv "$raw_tarball" "$tarball"
  echo "    -> $tarball"

  SETUP_PROGRESS="swapped"
  echo "==> Backing up example/package.json + yarn.lock + react-native.config.js"
  cp "$EXAMPLE/package.json" "$PKG_BACKUP"
  cp "$ROOT/yarn.lock" "$LOCK_BACKUP"
  cp "$EXAMPLE/react-native.config.js" "$RNCFG_BACKUP"

  echo "==> Injecting tarball as explicit dependency in example/package.json"
  jq --arg path "file:../.tarballs/$(basename "$tarball")" \
    '.dependencies["klaviyo-react-native-sdk"] = $path' \
    "$EXAMPLE/package.json" > "$EXAMPLE/package.json.tmp"
  mv "$EXAMPLE/package.json.tmp" "$EXAMPLE/package.json"

  # The committed example/react-native.config.js explicitly pins the SDK's
  # autolink root to the workspace root (so dev-mode autolinking finds the
  # workspace symlink). Override it to point at the tarball-extracted copy
  # for the duration of packed mode — otherwise iOS/Android autolinking
  # silently picks the workspace root and the test exercises dev mode.
  echo "==> Swapping example/react-native.config.js to packed-mode override"
  cat > "$EXAMPLE/react-native.config.js" <<'RNCFG'
// AUTO-GENERATED by pack-and-test.sh — do not commit.
// Restored to the workspace-mode version by `pack-and-test.sh restore`.
const path = require('path');
const pkg = require('../package.json');

module.exports = {
  project: {
    ios: {
      automaticPodsInstallation: true,
    },
  },
  dependencies: {
    [pkg.name]: {
      root: path.join(__dirname, 'node_modules', pkg.name),
      platforms: {
        ios: {},
        android: {},
      },
    },
  },
};
RNCFG

  SETUP_PROGRESS="installed"
  echo "==> Installing in example/ (drops --immutable, package.json changed)"
  (cd "$EXAMPLE" && yarn install)

  SETUP_PROGRESS="pods"
  echo "==> Running pod install in example/ios/"
  (cd "$EXAMPLE/ios" && bundle exec pod install)

  echo "$tarball" > "$MARKER"
  SETUP_PROGRESS="done"

  cat <<EOF

✓ Example app now consumes the packed SDK.

  Tarball: $tarball
  Marker:  $MARKER

Run the example app:
  yarn example ios               # interactive iOS launch
  yarn example android           # interactive Android launch
  yarn example build:ios         # non-interactive iOS build (good for CI)
  yarn example build:android     # non-interactive Android build (good for CI)

Restore workspace mode:
  $0 restore
EOF
}

cmd_restore() {
  if [[ ! -f "$MARKER" && ! -f "$PKG_BACKUP" && ! -f "$LOCK_BACKUP" && ! -f "$RNCFG_BACKUP" ]]; then
    echo "Already in workspace mode (no backup files present)."
    return 0
  fi

  if [[ -f "$PKG_BACKUP" ]]; then
    echo "==> Restoring example/package.json"
    mv "$PKG_BACKUP" "$EXAMPLE/package.json"
  else
    echo "WARNING: example/package.json backup missing; package.json may need manual review." >&2
  fi

  if [[ -f "$LOCK_BACKUP" ]]; then
    echo "==> Restoring yarn.lock"
    mv "$LOCK_BACKUP" "$ROOT/yarn.lock"
  fi

  if [[ -f "$RNCFG_BACKUP" ]]; then
    echo "==> Restoring example/react-native.config.js"
    mv "$RNCFG_BACKUP" "$EXAMPLE/react-native.config.js"
  fi

  echo "==> Reinstalling dependencies"
  (cd "$EXAMPLE" && yarn install)

  echo "==> Running pod install in example/ios/"
  (cd "$EXAMPLE/ios" && bundle exec pod install)

  rm -rf "$TARBALL_DIR"
  rm -f "$MARKER"

  echo "✓ Restored to workspace mode."
}

cmd_status() {
  if [[ -f "$MARKER" ]]; then
    echo "Mode: packed"
    echo "Tarball: $(cat "$MARKER")"
    [[ -f "$PKG_BACKUP" ]] && echo "Backup: $PKG_BACKUP"
  else
    echo "Mode: workspace"
  fi
}

case "${1:-}" in
  setup)   cmd_setup ;;
  restore) cmd_restore ;;
  status)  cmd_status ;;
  -h|--help|"") usage 0 ;;
  *) echo "Unknown command: ${1}" >&2; usage 1 ;;
esac
