name: Bug Report
description: Something isn't working as expected
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the Klaviyo React Native SDK!

        Before you submit your issue, please read our [contributing guidelines](https://github.com/klaviyo/klaviyo-react-native-sdk/blob/master/.github/CONTRIBUTING.md)
        and answer each question below with the relevant details for your bug.

        > Note: incomplete issues may be de-prioritized or closed.

        We welcome your input! If you have any code suggestions regarding your issue, feel free to
        [submit a pull request](https://github.com/klaviyo/klaviyo-react-native-sdk/pulls) after creating an issue.
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-react-native-sdk/blob/master/.github/CONTRIBUTING.md)
          required: true
        - label: I have determined whether this bug is also reproducible in a vanilla project, such as the example app in this repository.
          required: false
        - label: If possible, I've reproduced the issue using the `master` branch or latest release of this package.
          required: false
        - label: This issue hasn't been addressed in an [existing issue](https://github.com/klaviyo/klaviyo-react-native-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-react-native-sdk/pulls)
          required: true
  - type: textarea
    attributes:
      label: Description
      render: markdown
      description: |
        A short description of the incorrect behavior.

        If you think this issue has been recently introduced and did not occur in an earlier version, please note that.
        If possible, include the last version that the behavior was correct in addition to your current version.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      render: markdown
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      render: markdown
      description: Describe or copy/paste the behavior you observe. Include as much detail as possible, including stack traces or screenshots if available.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      render: markdown
      description: |
        Explanation of how to reproduce the incorrect behavior.

        This could include an attached project or link to code that is exhibiting the issue, and/or a screen recording.
      placeholder: |
        1. ...
    validations:
      required: true
  - type: input
    attributes:
      label: The Klaviyo React Native SDK version information
      description: The version of the Klaviyo React Native SDK used to reproduce this issue.
      placeholder: "'0.1.0' for example, or a commit hash"
    validations:
      required: true
  - type: input
    attributes:
      label: Environment Description
      description: Include the device model, OS version, and any other relevant development environment information.
      placeholder: 'Run `react-native info` in your project directory and paste the output here. Include additional information such as device model, OS version, etc.'
    validations:
      required: true
