# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!


linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'KlaviyoReactNativeSdkExample' do
  config = use_native_modules!

  use_frameworks! :linkage => :static

  # Manually override how the `klaviyo-react-native-sdk` is linked
  pod 'KlaviyoUI', :path => '../../../klaviyo-swift-sdk' # point to local Swift KlaviyoUI native library during development.         TODO: Revert this before release
  pod 'klaviyo-react-native-sdk/UI', :path => '../..'    # point to local React Native KlaviyoUI wrapper library during development. TODO: Revert this before release

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'KlaviyoReactNativeSdkExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

target 'KlaviyoReactNativeSdkExampleExtension' do
  use_frameworks! :linkage => :static
  pod 'KlaviyoSwiftExtension'
end
