name: Android CI

on:
  pull_request:

jobs:
  compile-android-new-arch:
    uses: ./.github/workflows/android-build.yml
    secrets: inherit
    with:
      new-architecture: 'true'

  compile-android-old-arch:
    uses: ./.github/workflows/android-build.yml
    secrets: inherit
    with:
      new-architecture: 'false'
